easy_admin:
    site_name: 'Julian Li'
    entities:
        # List the entity class name you want to manage
        Freelancer:
            class: App\Entity\Freelancer
        Education:
            class: App\Entity\Education
        Experience:
            class: App\Entity\Experience
        Skill:
            class: App\Entity\Skill
        SocialNetwork:
            class: App\Entity\SocialNetwork
        Project:
            class: App\Entity\Project
            list:
                fields: ['id', 'title', 'shortDescription', 'coverImageStyleSize', { property: 'coverImageUrl', type: 'image', base_path: '%app.path.projects%' }, 'tag', 'freelancer']
            show:
                fields: [{ property: 'coverImageUrl', type: 'image', base_path: '%app.path.projects%' }, { property: 'innerImageUrl', type: 'image', base_path: '%app.path.projects%' }]
            form:
                fields: ['title', 'shortDescription', { property: 'description', css_class: 'awesome-ckeditor', type: 'textarea'}, 'coverImageStyleSize', 'link', { property: 'coverImageFile', type: 'vich_image' }, { property: 'innerImageFile', type: 'vich_image' }, 'tag', 'freelancer']
        Post:
            class: App\Entity\Post
            list:
                fields: ['id', 'title', 'slug', 'isPublished', 'isPublic', { property: 'coverImageUrl', type: 'image', base_path: '%app.path.posts%' }, 'tags', 'createdAt']
            show:
                fields:
                    - { property: 'coverImageUrl', type: 'image', base_path: '%app.path.posts%' }
            form:
                fields: ['title', 'slug', 'isPublished', 'isPublic', { property: 'content', css_class: 'awesome-ckeditor', type: 'textarea' }, { property: 'coverImageFile', type: 'vich_image' }, 'tags', 'freelancer']
        Tag:
            class: App\Entity\Tag
    design:
        assets:
            js:
                - 'https://cdn.ckeditor.com/ckeditor5/1.0.0-beta.1/classic/ckeditor.js'
                - '/js/ckeditorcustom.js'