framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            sqs: enqueue://default?&topic[name]=julianli&queue[name]=julianli

        routing:
            # Route your messages to the transports
            'App\Requests\Contact': sqs
