security:
    encoders:
        App\Entity\Freelancer:
            algorithm: bcrypt
            cost:      12

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Freelancer
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/api/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
