version: "2"

services:
    app:
        image: julianli/julianli_app
        container_name: app
        depends_on:
            - db
            - redis
        ports:
            - "8888:80"
        volumes:
            - .:/app
            - /app/var/cache
            - /app/var/sessions
            - ./docker/nginx.conf:/etc/nginx/nginx.conf

    db:
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./lib:/var/lib/mysql

    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"