version: "3.2"

services:
    app:
        build: docker/dev
        container_name: app
        depends_on:
            - db
            - redis
        ports:
            - "8888:80"
        volumes:
            - .:/app

    db:
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./lib:/var/lib/mysql

    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"

    blackfire:
        image: blackfire/blackfire
        environment:
            # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
            # You can also use global environment credentials :
            # BLACKFIRE_SERVER_ID: SERVER-ID
            # BLACKFIRE_SERVER_TOKEN: SERVER-TOKEN