version: "3.2"

services:
    blackfire:
        image: blackfire/blackfire
        environment:
            # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
            # You can also use global environment credentials :
            # BLACKFIRE_SERVER_ID: SERVER-ID
            # BLACKFIRE_SERVER_TOKEN: SERVER-TOKEN
